var settings = {}
settings.pg = {};
settings.application = {};
settings.tilestream = {};
settings.application.port = 80;
settings.pg.username = '${HDX_GISDB_USER}';
settings.pg.password = '${HDX_GISDB_PASS}';
settings.pg.server = '${HDX_GISDB_ADDR}';
settings.pg.port = '${HDX_GISDB_PORT}';
settings.pg.database = '${HDX_GISDB_DB}';
settings.pg.featureLimit = 1000; //how many features to return by default
settings.displayViews = true;
settings.displayTables = true;
settings.pg.noFlyList = ["att_0"];
settings.application.formatList =[ 'html', 'GeoJSON', 'esriJSON'];
settings.application.geoJsonOutputFolder = "/public/geojson/output/";
settings.application.publichost = ""; //like myhost.com. Keep this empty if you want to use the default host
settings.application.publicport = "80";
settings.epxressSessionSecret = "secret";
settings.mongodb = {};
settings.mongodb.db = "mongodb://localhost/authentication";
settings.facebook = {};
settings.facebook.appid = "12345";
settings.facebook.secret = "secret";
settings.leaflet = {};
settings.leaflet.js = 'http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js?2';
settings.leaflet.css = 'http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css';
settings.jquery = {};
settings.jquery.js = 'http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js';
settings.acceptableReferrers = [];
settings.referrerCheckHints = [];
module.exports = settings;
